### ISSUE TITLE
[rich-text-react-renderer] React 17 support?

### ISSUE THREAD

**Issue by CarpenterBug** [contentful/rich-text#199] opened 2021-01-16 18:03 UTC
When installing the `rich-text-react-renderer`, I got the following error:
```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: agency-website@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from @contentful/rich-text-react-renderer@14.1.2
npm ERR! node_modules/@contentful/rich-text-react-renderer
npm ERR!   @contentful/rich-text-react-renderer@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
...
```

That said, do you know when React 17 support is expected?

Thank you in advance.

**Comment by Weffe** [comment] 2021-02-05 19:11
Getting the same error on npm v7.5.2. Would be nice to get the peer dependency version bumped or allow v17.

```json
"peerDependencies": {
    "react": "^16.8.6 || ^17.0.0",
    "react-dom": "^16.8.6 || ^17.0.0"
},
```

**Comment by innowhat** [comment] 2021-02-11 04:48
Same here with React 17.0.1  run `npm update` to reproduce.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mysite@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from @contentful/rich-text-react-renderer@14.1.2
npm ERR! node_modules/@contentful/rich-text-react-renderer
npm ERR!   @contentful/rich-text-react-renderer@"^14.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Comment by DanweDE** [comment] 2021-03-17 10:01
Thank you for the request. We've added this to our backlog for now.

Since this is an open source repo, please also feel free to prepare a PR with this change.

**Comment by imshuffling** [comment] 2021-04-06 14:54
Any update on this @DanweDE ? :)

**Comment by sahanatroam** [comment] 2021-04-08 03:32
Hey @DanweDE 
Please do let me know how I could help to resolve this. Hope the pull request above helps.

**Comment by djagya** [comment] 2021-04-12 10:38
Hello! Sorry for the delay, everyone. The PR is now merged (thanks @sahanatroam!) and released in `@contentful/rich-text-react-renderer@14.1.3`.

**Closed by djagya** 2021-04-12 10:38 UTC
